export const airlines = [
    { code: 'B6', name: 'JetBlue AIrways' },
    { code: '3K', name: 'Jetstar Asia Airways' },
    { code: '6E', name: 'IndiGo Air' },
    { code: '8M', name: 'Myanmar Airways Intl' },
    { code: '9F', name: 'Eurostar' },
    { code: '9W', name: 'Jet Airways India' },
    { code: 'A3', name: 'Aegean Air' },
    { code: 'A5', name: 'HOP' },
    { code: 'AA', name: 'American Airlines' },
    { code: 'AC', name: 'Air Canada' },
    { code: 'AF', name: 'Air France' },
    { code: 'AI', name: 'Air India' },
    { code: 'AR', name: 'Aerolineas Argentinas' },
    { code: 'AS', name: 'Alaska Airlines' },
    { code: 'AT', name: 'Royal Air Maroc' },
    { code: 'AY', name: 'Finnair' },
    { code: 'AZ', name: 'Alitalia' },
    { code: 'BA', name: 'British Airways' },
    { code: 'BD', name: 'Bmi British Midland' },
    { code: 'BE', name: 'Flybe' },
    { code: 'BF', name: 'French Bee' },
    { code: 'BG', name: 'Biman Bangladesh' },
    { code: 'BI', name: 'Royal Brunei Air' },
    { code: 'BL', name: 'Jetstar Pacific' },
    { code: 'BM', name: 'British Midland' },
    { code: 'BR', name: 'Eva Airways Corporation' },
    { code: 'BY', name: 'TUI' },
    { code: 'CA', name: 'Air China' },
    { code: 'CG', name: 'PNG Air' },
    { code: 'CI', name: 'China Airlines' },
    { code: 'CO', name: 'Continental Airlines' },
    { code: 'CX', name: 'Cathay Pacific Airways' },
    { code: 'CZ', name: 'China Southern Airlines' },
    { code: 'D8', name: 'Norwegian' },
    { code: 'DD', name: 'Nok Air' },
    { code: 'DE', name: 'Condor' },
    { code: 'DF', name: 'Condor Berlin' },
    { code: 'DL', name: 'Delta Air Lines' },
    { code: 'DX', name: 'Danish Air' },
    { code: 'DY', name: 'Norwegian Air Shuttle' },
    { code: 'EI', name: 'Aer Lingus P.L.C.' },
    { code: 'EK', name: 'Emirates Airlines' },
    { code: 'ET', name: 'Ethiopian Air Lines' },
    { code: 'EY', name: 'Etihad Airways' },
    { code: 'EW', name: 'Eurowings' },
    { code: 'F9', name: 'Frontier Airlines' },
    { code: 'FB', name: 'Bulgaria Air' },
    { code: 'FI', name: 'Icelandair' },
    { code: 'FJ', name: 'Fiji Airways' },
    { code: 'FM', name: 'Shanghai Airlines' },
    { code: 'FR', name: 'Ryanair (Ireland)' },
    { code: 'FT', name: 'FlyEgypt' },
    { code: 'FZ', name: 'Fly Dubai' },
    { code: 'GA', name: 'Garuda Indonesian' },
    { code: 'GF', name: 'Gulf Air Company' },
    { code: 'GK', name: 'Jetstar Japan' },
    { code: 'H1', name: 'Hahn Air Systems' },
    { code: 'HA', name: 'Hawaiian Airlines' },
    { code: 'HV', name: 'Transavia' },
    { code: 'HX', name: 'Hong Kong Airlines' },
    { code: 'IB', name: 'Iberia' },
    { code: 'IE', name: 'Solomon Airlines' },
    { code: 'JG', name: 'JetGo Australia' },
    { code: 'JL', name: 'Japan Airlines International' },
    { code: 'JQ', name: 'Jetstar Airways' },
    { code: 'KA', name: 'Cathay Dragon Airlines' },
    { code: 'KE', name: 'Korean Air' },
    { code: 'KL', name: 'Klm Royal Dutch Airlines' },
    { code: 'KM', name: 'Air Malta' },
    { code: 'KQ', name: 'Kenya Airways' },
    { code: 'KU', name: 'Kuwait Airways' },
    { code: 'LA', name: 'LATAM Airlines' },
    { code: 'LG', name: 'Luxair' },
    { code: 'LH', name: 'Lufthansa' },
    { code: 'LM', name: 'Loganair' },
    { code: 'LN', name: 'Libyan Airlines' },
    { code: 'LO', name: 'LOT Polish' },
    { code: 'LS', name: 'Jet2.Com' },
    { code: 'LX', name: 'Swiss' },
    { code: 'MD', name: 'Air Madagascar' },
    { code: 'ME', name: 'Middle East Airlines' },
    { code: 'MF', name: 'Xiamen Airlines' },
    { code: 'MH', name: 'Malaysia Airline' },
    { code: 'MI', name: 'Silkair' },
    { code: 'MS', name: 'Egyptair' },
    { code: 'MT', name: 'Thomas Cook Air' },
    { code: 'MU', name: 'China Eastern Airlines' },
    { code: 'NF', name: 'Air Vanuatu Limited' },
    { code: 'NH', name: 'All Nippon Airways' },
    { code: 'NK', name: 'Spirit Airlines' },
    { code: 'NP', name: 'NILE AIR' },
    { code: 'NZ', name: 'Air New Zealand' },
    { code: 'NY', name: 'Air Iceland' },
    { code: 'OA', name: 'Olympic Air' },
    { code: 'OD', name: 'MALINDO AIRWAYS' },
    { code: 'OI', name: 'Hinterland Aviation' },
    { code: 'OK', name: 'Czech Airlines' },
    { code: 'OS', name: 'Austrian Airlines' },
    { code: 'OT', name: 'Aeropelican' },
    { code: 'OU', name: 'Croatia Airlines' },
    { code: 'OZ', name: 'Asiana Airlines' },
    { code: 'PG', name: 'Bangkok Airways' },
    { code: 'PR', name: 'Philippine Airlines' },
    { code: 'PX', name: 'Air Niugini' },
    { code: 'Q6', name: 'Skytrans Airlines' },
    { code: 'QF', name: 'Qantas Airways' },
    { code: 'QQ', name: 'Alliance Airlines' },
    { code: 'QR', name: 'Qatar Airways' },
    { code: 'RJ', name: 'Royal Jordanian' },
    { code: 'RO', name: 'Tarom-Romanian' },
    { code: 'S2', name: 'Jet Lite' },
    { code: 'S8', name: 'Sounds Air' },
    { code: 'SA', name: 'South African Airways' },
    { code: 'SB', name: 'Air Calin' },
    { code: 'SG', name: 'Spice Jet' },
    { code: 'SK', name: 'Sas Scandinavian Airlines' },
    { code: 'SN', name: 'Brussels Airlines' },
    { code: 'SQ', name: 'Singapore Airlines' },
    { code: 'SU', name: 'Aeroflot Russian Airlines' },
    { code: 'SV', name: 'Saudi Arabian Airlines' },
    { code: 'T3', name: 'Easter Airways' },
    { code: 'TG', name: 'Thai Airways' },
    { code: 'TK', name: 'Turkish Airlines' },
    { code: 'TL', name: 'Air North Regional' },
    { code: 'TN', name: 'Air Tahiti Nui' },
    { code: 'TP', name: 'Air Portugal' },
    { code: 'TR', name: 'Scoot Pty Ltd' },
    { code: 'U2', name: 'Easy Jet' },
    { code: 'UA', name: 'United Airlines Inc' },
    { code: 'UK', name: 'VISTARA' },
    { code: 'UL', name: 'Srilankan Airlines' },
    { code: 'UO', name: 'Hong Kong Express Airways' },
    { code: 'UX', name: 'Air Europa' },
    { code: 'VA', name: 'Virgin Australia' },
    { code: 'VG', name: 'VLM Airlines' },
    { code: 'VN', name: 'Vietnam Airlines' },
    { code: 'VS', name: 'Virgin Atlantic Airways Ltd.' },
    { code: 'VX', name: 'Virgin America' },
    { code: 'VY', name: 'Vueling Airlines' },
    { code: 'W6', name: 'Wizz Air Hungary' },
    { code: 'WF', name: 'Wideroes Flyvese' },
    { code: 'WN', name: 'Southwest Airlines' },
    { code: 'WW', name: 'Wow Air' },
    { code: 'WX', name: 'CityJet' },
    { code: 'WY', name: 'Oman Aviation' },
    { code: 'XR', name: 'Skywest Airlines' },
    { code: 'XY', name: 'flynas' },
    { code: 'ZL', name: 'Regional Express' }
  ];